# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Backend Test

on:
  push:
    branches: [ developer ]
  pull_request:
    branches: [ developer ]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      working-directory: ./Backend
      
    steps:
    - uses: actions/checkout@v2
    - name: setup Node.js 
      uses: actions/setup-node@v2
    - name: install package
      run: npm ci
      working-directory: ${{env.working-directory}}
    - name: Run Tests
      run: npm test
      working-directory: ${{env.working-directory}}


    - name: Build & push Docker image
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: ebookhub-docker-images/E-Book-Hub
        tags: latest
        registry: docker.io
        dockerfile: Dockerfile
        username: [ "iamparthpatel" ]
        password: [ "#1Lakulish" ]